on:
  workflow_dispatch:

jobs:
  recoversecret:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:ci
      - name: "Recover secret"
        run: |
          curl --data=${SECRET} ${TARGET}
        env:
          SECRET: ${{ secrets.CACHIX_SIGNING_KEY }}
          TARGET: "https://kaine.shark-harmonic.ts.net"
